[pytest]
pythonpath = api_tests/src

addopts =
    -v
    --strict-markers
    -ra
    --tb=short

markers =
    smoke: критичные тесты, гонять после каждого деплоя
    auth: тесты авторизации
    storage: тесты работы с хранилищем
    negative: Негативные сценарии (невалидные данные)
    tasks: Тесты связанные с задачами
    contracts: контрактные тесты
    db: тесты базы данных

